version: '3.3'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - ./src/db_init:/docker-entrypoint-initdb.d
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:5000"

